#pragma once

#define DEFAULT_REGISTRY_SETTING_PATH	"MY_TOOL\\DataAnalysis\\"

#define DATA_ACQUISITION_MODE	1
#define DATA_ANALYZE_MODE		0

#define MAX_COM_PORT_SIZE	100  //최대 저장 PortCount

typedef enum {
	SEQ_HEADER_CHECK_FIRST,
	SEQ_HEDER_CHECK_UNTIL_LAST,
	SEQ_GET_GROUP,
	SEQ_TEXT_VALUE_GET,
	SEQ_BIN_VALUE_GET,
	SEQ_GET_TAIL_CHECK_FIRST,
	SEQ_GET_TAIL_CHECK_UNTIL_LAST,
	SEQ_WAIT_END,
} SEQ_e;